### ISSUE TITLE
Error when running sharpy unittest: module scipy.sparse._sputils not found

### ISSUE THREAD

**Issue by EmilDoyle19** [ImperialCollegeLondon/sharpy#227]
When running a python -m unittest for my sharpy installation on the Debian GNU/Linux 11 spitfire.ae.ic.ac.uk systems provided by the aero department, I get the error that the module scipy.sparse._sputils is not found. This happened using a quick installation, with Fortran and C++ compilers. I'm using the latest version of sharpy. Here's one of the tests that failed:

======================================================================
ERROR: test_flutter (tests.linear.goland_wing.test_goland_flutter.TestGolandFlutter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/emd19/sharpy/tests/linear/goland_wing/test_goland_flutter.py", line 269, in test_flutter
    self.setup()
  File "/home/emd19/sharpy/tests/linear/goland_wing/test_goland_flutter.py", line 230, in setup
    self.data = sharpy.sharpy_main.main(['', ws.route + ws.case_name + '.sharpy'])
  File "/home/emd19/sharpy/sharpy/sharpy_main.py", line 43, in main
    import sharpy.solvers
  File "/home/emd19/sharpy/sharpy/solvers/__init__.py", line 15, in <module>
    solver_interface.solvers[file] = importlib.import_module(import_path + "." + file)
  File "/home/emd19/anaconda3/envs/sharpy_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/emd19/sharpy/sharpy/solvers/lindynamicsim.py", line 6, in <module>
    import sharpy.linear.src.libss as libss
  File "/home/emd19/sharpy/sharpy/linear/src/libss.py", line 66, in <module>
    import sharpy.linear.src.libsparse as libsp
  File "/home/emd19/sharpy/sharpy/linear/src/libsparse.py", line 38, in <module>
    from scipy.sparse._sputils import upcast_char
ModuleNotFoundError: No module named 'scipy.sparse._sputils'

**Comment by alexruiz95** [comment]
I received the same error for the scipy.sparse._sputils when running the provided examples files. This was on a fresh install in a linux ubuntu virtual machine.

**Comment by sduess** [comment]
Hello,

We have recently updated SHARPy's python version from 3.7 to 3.10 (see #222 ). Please update the python version of your machine accordingly which should resolve the error.

**Comment by nicolalc7** [comment]
Even though I have python 3.10.9 in my machine, the version shown when entering python --version inside the sharpy_env environment is still 3.7.5, and I still get the aforementioned error.
